version: "3"
services:
  api:
    build: .
    ports:
      - "4000:4000"
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_DB: system
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
